version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "01:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/typescript.novaextension"
    schedule:
      interval: monthly
      time: "01:00"
    open-pull-requests-limit: 10
