blank_issues_enabled: true
contact_links:
  - name: Report to Panic
  - url: "https://nova.app/help/?ext=TypeScript%20(apexskier.typescript)%20(reported%20fromhttps%3A%2F%2Fgithub.com%2Fapexskier%2Fnova-typescript%2Fissues%2Fnew)"
  - about: Please report any hard crashes directly to Panic.
